version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: first_ci_cd
    environment:
      POSTGRES_DB: first_ci_cd
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d first_ci_cd"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - first_ci_cd_pg_data:/var/lib/postgresql/data

volumes:
  first_ci_cd_pg_data:
